version: '2'
services:

  php:
    image: bitnami/php-fpm:latest
    ports:
      - 9000:9000
    volumes:
      - ./wordpress:/app:rw
  mysql:
    image: mysql:5.7
    env_file:
      - ./.env
    volumes:
      - ./.docker/data/mysql/:/var/lib/mysql
      - ./.docker/logs/mysql/:/var/log/mysql
    ports:
      - "3307:3306"
    container_name: wp_mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      -  8080:80
    env_file:
      - ./.env
    environment:
      PMA_HOST: mysql
      VIRTUAL_HOST: phpmyadmin.wp.local  
    container_name: wp_phpmyadmin
  app_dev:
    image: 'bitnami/apache:latest'
    container_name: wp_app
    #build: ./wordpress/
    environment:
      - VIRTUAL_HOST=app.wp.local
    volumes : 
      - ./wordpress/config/wdpress.conf:/vhosts/myapp.conf:ro
      - ./wordpress:/app:rw
    restart: always
    ports:
      - 8100:8080
      #- 443:8443
    links:
      - "mysql:wp_mysql"
    depends_on:
      - php